config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :candidates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_finish)

    if @candidate.save
      redirect_to candidates_path, notice: "新增候選人成功!"
    else
      render :new
    end
  end

  def edit
    @candidate = Candidate.find_by(id: params[:id])
  end

  def update
    @candidate = Candidate.find_by(id: params[:id])

    if @candidate.update(candidate_finish)
      redirect_to candidates_path, notice: "編輯候選人成功!"
    else
      render :edit
    end
  end

  def destroy
    @candidate = Candidate.find_by(id: params[:id])
    @candidate.destroy if @candidate
    redirect_to candidates_path, notice: "刪除候選人成功!"
  end

  private

  def candidate_finish
    params.require(:candidate).permit(:name, :age, :party, :politics)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(candidate) do |form| %>
  <%= form.label :name, "姓名" %>
  <%= form.text_field :name %><br>

  <%= form.label :age, "年齡" %>
  <%= form.text_field :age %><br>
  
  <%= form.label :party, "政黨" %>
  <%= form.text_field :party %><br>

  <%= form.label :politics, "政見" %>
  <%= form.text_field :politics %><br>


  <%= form.submit %>
<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render "form", candidate: @candidate %>

<%= link_to '回候選人列表', candidates_path, class: "back_to_index" %>

app/views/candidates/index.html.erb
<% flash.each do |type, message| %>
  <div>
    <%= message %>
  </div>
<% end %>

<h1>候選人列表</h1>

<%= link_to "新增候選人", new_candidate_path, class: "add_candidate" %>

<table>
  <thead>
    <tr>
      <td>投票</td>
      <td>候選人姓名</td>
      <td>年齡</td>
      <td>政黨</td>
      <td>政見</td>
      <td>得票數</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td><%= link_to "投！", "#" %></td>
      <td><%= candidate.name %></td>
      <td><%= candidate.age %> 歲</td>
      <td><%= candidate.party %></td>
      <td><%= candidate.politics %></td>
      <td><%= candidate.votes %></td>
      <td>
        <%= link_to "編輯", edit_candidate_path(candidate) %>
        <%= link_to "刪除", candidate_path(candidate), method: "delete", data: {confirm: "確認刪除嗎？" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render "form", candidate: @candidate %>

<%= link_to '回候選人列表', candidates_path, class: "back_to_index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candidates02</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>